### ISSUE TITLE
Reasoning Performance drop for Pruning

### ISSUE THREAD

**Issue by jojo23333** [pprp/Awesome-LLM-Prune#1]
Hi Peijie, Thanks for the effort to put the paper list together. I'm Muchen from UBC working on LLM for reasoning. I noticed that among pruning literature people rarely show reasoning-related tasks (e.g. math, coding, logic bench). I noticed a few signs that reasoning capability degenerates a lot in several papers (e.g. Table 13 in this paper https://arxiv.org/pdf/2310.06694 ),  is there any other paper showing such results? do you mind share your opinion on this matter?

**Comment by pprp** [comment]
@jojo23333  there are some evaluation papers on LLM pruning and Quantization:

https://arxiv.org/abs/2402.18158
https://arxiv.org/abs/2405.06001

Also, you can refer to these two repo:

https://github.com/pprp/Awesome-LLM-Prune (pay attention to `benchmark`)
https://github.com/pprp/Awesome-LLM-quantization

**Comment by jojo23333** [comment]
Thank you for the information! I'll take a look
